#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U "${POSTGRES_USER}" <<-EOSQL
  CREATE USER ${POSTGRES_USER}_test;
  CREATE DATABASE ${POSTGRES_DB}_test;
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB}_test TO ${POSTGRES_USER}_test;
EOSQL
